name: Delete Neon Branch with GitHub Actions Demo
run-name: Delete a Neon Branch by name 🚀

on:
  pull_request:
    types:
      - closed

jobs:
  delete-neon-branch-by-name:
    runs-on: ubuntu-latest  # This was missing in your original code
    steps:
    - name: Delete Neon Branch
      uses: neondatabase/delete-branch-by-name-action@main
      with:
        project_id: round-voice-73097919
        branch_name: neon-branch
        api_key: ${{ secrets.NEON_API_KEY }}
